"use client";

import Link from "next/link";import {useEffect,useState} from "react";
import ProductShell,{PageState,TechnicalDetails} from "./ProductShell";import {apiRequest,readProductSession} from "../lib/product-session";

export default function ZiweiCompleteJourney(){
 const [profileId,setProfileId]=useState("");const [year,setYear]=useState("");const [month,setMonth]=useState("");const [day,setDay]=useState("");const [hour,setHour]=useState("0");const [sex,setSex]=useState("male");const [leap,setLeap]=useState(false);const [run,setRun]=useState<any>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 useEffect(()=>setProfileId(readProductSession().subject?.id||""),[]);
 async function execute(){setError("");if(!year||!month||!day){setError("请录入经过人工确认的农历年月日。当前不会自动把公历静默转换为农历。");return}setBusy(true);try{setRun(await apiRequest<any>("/api/v1/traditional-complete/execute",{method:"POST",body:JSON.stringify({profile_record_id:profileId,ziwei:{lunar_year:Number(year),lunar_month:leap?-Number(month):Number(month),lunar_day:Number(day),hour_index:Number(hour),traditional_sex:sex,target_date:new Date().toISOString().slice(0,10),method_profile:{profile_id:"ziwei-sanhe-complete-v1",version:"1.0.0",leap_month_policy:"iztro_fix_leap_true"}}})}))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 if(!profileId)return <ProductShell title="紫微机械结构" eyebrow="合参 · 紫微"><PageState kind="insufficient" title="请先建立主体"><Link className="product-button" href="/onboarding">建立主体</Link></PageState></ProductShell>;
 const system=run?.result?.module_results?.["traditional-complete"]?.result?.systems?.find((v:any)=>v.system==="ziwei");const result=system?.result;const mechanical=run?.mechanical_results?.ziwei;
 return <ProductShell title="紫微三合研究结构" eyebrow="合参 · 紫微" status="research_active · UNCONFIRMED"><aside className="privacy-note"><b>受限三合研究 Profile</b><p>请输入人工确认的农历资料。闰月策略固定显示，不隐藏选择；本页不宣称覆盖所有紫微门派。</p></aside><section className="product-form"><div className="field-pair"><label>农历年<input type="number" min="1600" max="2600" value={year} onChange={e=>setYear(e.target.value)}/></label><label>农历月<input type="number" min="1" max="12" value={month} onChange={e=>setMonth(e.target.value)}/></label></div><div className="field-pair"><label>农历日<input type="number" min="1" max="30" value={day} onChange={e=>setDay(e.target.value)}/></label><label>时支序号（子=0）<input type="number" min="0" max="11" value={hour} onChange={e=>setHour(e.target.value)}/></label></div><label className="check-field"><input type="checkbox" checked={leap} onChange={e=>setLeap(e.target.checked)}/><span>这是闰月</span></label><label>传统性别参数<select value={sex} onChange={e=>setSex(e.target.value)}><option value="male">男</option><option value="female">女</option></select></label><button className="product-button" disabled={busy} onClick={execute}>{busy?"正在计算…":"执行紫微研究 Profile"}</button>{error&&<p role="alert" className="field-error">{error}</p>}</section>{system&&<><section className="scope-card"><h2>宫盘摘要</h2><p>命宫 {result.life_palace_branch}；身宫 {result.body_palace_branch}；五行局 {result.five_element_bureau}</p><p>十二宫 {result.palaces?.length}；主星结构 {mechanical?.palaces?.length||0} 宫；Profile {system.profile_id}；状态 {system.status}</p></section><TechnicalDetails><pre>{JSON.stringify({profile:system.profile_id,ruleset:system.ruleset_version,mechanical,result,output_hash:run.result.output_hash,trace_hash:run.result.trace_hash},null,2)}</pre></TechnicalDetails></>}</ProductShell>;
}
