-- Sprint 0 migration draft. Review before applying.
-- PostgreSQL 16. UUIDv7 values are generated by the application.
BEGIN;

CREATE TABLE users (
  id uuid PRIMARY KEY,
  email_ciphertext bytea NOT NULL,
  role text NOT NULL CHECK (role IN ('owner','member','viewer')),
  status text NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

CREATE TABLE profiles (
  id uuid PRIMARY KEY,
  owner_id uuid NOT NULL REFERENCES users(id),
  display_name_ciphertext bytea,
  gender_code text,
  timezone text NOT NULL,
  calendar_type text NOT NULL CHECK (calendar_type IN ('gregorian','lunar')),
  birth_date_ciphertext bytea NOT NULL,
  birth_time_ciphertext bytea,
  birth_time_precision text NOT NULL CHECK (birth_time_precision IN ('minute','double_hour','half_day','unknown')),
  birth_location_ciphertext bytea,
  latitude_ciphertext bytea,
  longitude_ciphertext bytea,
  consent_version text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

CREATE TABLE evidence_items (
  id uuid PRIMARY KEY,
  profile_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  type text NOT NULL,
  payload_encrypted bytea NOT NULL,
  observed_from date,
  observed_to date,
  frequency smallint CHECK (frequency BETWEEN 0 AND 10),
  vividness smallint CHECK (vividness BETWEEN 0 AND 10),
  source_reliability numeric(4,3) NOT NULL CHECK (source_reliability BETWEEN 0 AND 1),
  user_confirmed boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE rulesets (
  id uuid PRIMARY KEY,
  name text NOT NULL,
  version text NOT NULL,
  status text NOT NULL CHECK (status IN ('draft','active','retired')),
  checksum text NOT NULL CHECK (checksum ~ '^[a-f0-9]{64}$'),
  manifest_json jsonb NOT NULL,
  approved_by uuid[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  activated_at timestamptz,
  UNIQUE(name, version)
);

CREATE TABLE chart_snapshots (
  id uuid PRIMARY KEY,
  profile_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  engine text NOT NULL CHECK (engine IN ('bazi','ziwei','yijing')),
  method_id text NOT NULL,
  engine_version text NOT NULL,
  input_hash text NOT NULL CHECK (input_hash ~ '^[a-f0-9]{64}$'),
  result_json jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(profile_id, engine, method_id, engine_version, input_hash)
);

CREATE TABLE analysis_runs (
  id uuid PRIMARY KEY,
  profile_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  ruleset_id uuid NOT NULL REFERENCES rulesets(id),
  status text NOT NULL CHECK (status IN ('queued','normalizing','calculating','counterchecking','complete','failed','cancelled')),
  input_snapshot_encrypted bytea NOT NULL,
  input_hash text NOT NULL CHECK (input_hash ~ '^[a-f0-9]{64}$'),
  random_seed bigint NOT NULL,
  data_completeness numeric(4,3) NOT NULL CHECK (data_completeness BETWEEN 0 AND 1),
  result_json jsonb,
  error_code text,
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);

CREATE TABLE hypotheses (
  id uuid PRIMARY KEY,
  analysis_run_id uuid NOT NULL REFERENCES analysis_runs(id) ON DELETE CASCADE,
  archetype_id text NOT NULL,
  raw_score numeric(6,5) NOT NULL,
  calibrated_score numeric(6,5) NOT NULL CHECK (calibrated_score BETWEEN 0 AND 1),
  confidence_level text NOT NULL CHECK (confidence_level IN ('open','medium_resonance','strong_resonance')),
  positive_evidence jsonb NOT NULL,
  counter_evidence jsonb NOT NULL,
  system_coverage jsonb NOT NULL,
  why_may_be_false text NOT NULL,
  rank smallint NOT NULL CHECK (rank > 0)
);

CREATE TABLE past_life_nodes (
  id uuid PRIMARY KEY,
  analysis_run_id uuid NOT NULL REFERENCES analysis_runs(id) ON DELETE CASCADE,
  kind text NOT NULL CHECK (kind IN ('active','root','practice_peak','achievement_peak','karmic')),
  era_symbol text,
  region_symbols jsonb,
  archetype_ids jsonb NOT NULL,
  gravity numeric(6,5) NOT NULL CHECK (gravity BETWEEN 0 AND 1),
  confidence_json jsonb NOT NULL,
  attributes_json jsonb NOT NULL
);

CREATE TABLE life_chart_points (
  id uuid PRIMARY KEY,
  analysis_run_id uuid NOT NULL REFERENCES analysis_runs(id) ON DELETE CASCADE,
  scenario text NOT NULL CHECK (scenario IN ('original','balanced','vow')),
  dimension text NOT NULL,
  age_from numeric(5,2) NOT NULL,
  age_to numeric(5,2) NOT NULL CHECK (age_to > age_from),
  open_value numeric(6,2) NOT NULL CHECK (open_value BETWEEN 0 AND 100),
  high_value numeric(6,2) NOT NULL CHECK (high_value BETWEEN 0 AND 100),
  low_value numeric(6,2) NOT NULL CHECK (low_value BETWEEN 0 AND 100),
  close_value numeric(6,2) NOT NULL CHECK (close_value BETWEEN 0 AND 100),
  confidence_low numeric(6,2) NOT NULL CHECK (confidence_low BETWEEN 0 AND 100),
  confidence_high numeric(6,2) NOT NULL CHECK (confidence_high BETWEEN 0 AND 100),
  drivers_json jsonb NOT NULL,
  CHECK (low_value <= open_value AND low_value <= close_value),
  CHECK (high_value >= open_value AND high_value >= close_value),
  CHECK (confidence_low <= confidence_high)
);

CREATE TABLE relationship_subjects (
  id uuid PRIMARY KEY,
  profile_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  mode text NOT NULL CHECK (mode IN ('consented_profile','anonymous_event')),
  linked_profile_id uuid REFERENCES profiles(id),
  alias_ciphertext bytea,
  consent_record_encrypted bytea,
  consented_at timestamptz,
  consent_revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (
    (mode = 'consented_profile' AND linked_profile_id IS NOT NULL AND consent_record_encrypted IS NOT NULL)
    OR (mode = 'anonymous_event' AND linked_profile_id IS NULL)
  )
);

CREATE TABLE journal_entries (
  id uuid PRIMARY KEY,
  profile_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  entry_date date NOT NULL,
  content_encrypted bytea NOT NULL,
  tags_encrypted bytea,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE profile_versions (
  id uuid PRIMARY KEY,
  profile_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  analysis_run_id uuid REFERENCES analysis_runs(id) ON DELETE SET NULL,
  version_no integer NOT NULL CHECK (version_no > 0),
  snapshot_encrypted bytea NOT NULL,
  change_summary_json jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(profile_id, version_no)
);

CREATE TABLE knowledge_documents (
  id uuid PRIMARY KEY,
  tradition text NOT NULL,
  title text NOT NULL,
  author text,
  edition text,
  license_status text NOT NULL,
  source_uri text,
  checksum text NOT NULL CHECK (checksum ~ '^[a-f0-9]{64}$'),
  status text NOT NULL CHECK (status IN ('pending','approved','rejected','retired')),
  metadata_json jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE knowledge_chunks (
  id uuid PRIMARY KEY,
  document_id uuid NOT NULL REFERENCES knowledge_documents(id) ON DELETE CASCADE,
  locator text NOT NULL,
  content text NOT NULL,
  tags text[] NOT NULL,
  embedding_model_id text,
  embedding_dimensions integer CHECK (embedding_dimensions > 0),
  embedding double precision[],
  token_count integer NOT NULL CHECK (token_count >= 0),
  approved boolean NOT NULL DEFAULT false,
  CHECK (
    (embedding IS NULL AND embedding_model_id IS NULL AND embedding_dimensions IS NULL)
    OR
    (embedding IS NOT NULL AND embedding_model_id IS NOT NULL
      AND embedding_dimensions = cardinality(embedding))
  )
);

-- Do not add a production ANN index until the embedding model and dimension
-- are frozen. Then use a model-scoped expression/partial index, for example:
-- A model-scoped pgvector column/index may be added only after D-015 is frozen.
-- WHERE embedding_model_id = '<confirmed_model_id>';

CREATE TABLE generated_reports (
  id uuid PRIMARY KEY,
  analysis_run_id uuid NOT NULL REFERENCES analysis_runs(id) ON DELETE CASCADE,
  prompt_version text NOT NULL,
  model_provider text NOT NULL,
  model_name text NOT NULL,
  knowledge_chunk_ids uuid[] NOT NULL,
  structured_output jsonb NOT NULL,
  rendered_markdown text NOT NULL,
  status text NOT NULL CHECK (status IN ('complete','validation_failed','provider_unavailable')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE audit_events (
  id bigserial PRIMARY KEY,
  actor_id uuid,
  action text NOT NULL,
  resource_type text NOT NULL,
  resource_id uuid,
  metadata_redacted jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX profiles_owner_created_idx ON profiles(owner_id, created_at);
CREATE INDEX evidence_profile_created_idx ON evidence_items(profile_id, created_at);
CREATE INDEX charts_profile_created_idx ON chart_snapshots(profile_id, created_at);
CREATE INDEX runs_profile_created_idx ON analysis_runs(profile_id, created_at);
CREATE INDEX hypotheses_run_idx ON hypotheses(analysis_run_id, rank);
CREATE INDEX nodes_run_idx ON past_life_nodes(analysis_run_id);
CREATE INDEX life_points_run_idx ON life_chart_points(analysis_run_id);
CREATE INDEX relations_profile_idx ON relationship_subjects(profile_id, created_at);
CREATE INDEX journal_profile_created_idx ON journal_entries(profile_id, created_at);
CREATE INDEX versions_profile_created_idx ON profile_versions(profile_id, created_at);
CREATE INDEX reports_run_created_idx ON generated_reports(analysis_run_id, created_at);
CREATE INDEX audit_created_idx ON audit_events(created_at);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE evidence_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE chart_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE analysis_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE relationship_subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE journal_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE profile_versions ENABLE ROW LEVEL SECURITY;

-- API transaction must SET LOCAL app.current_user_id after authenticating.
CREATE POLICY profiles_owner_policy ON profiles
  USING (owner_id = nullif(current_setting('app.current_user_id', true), '')::uuid)
  WITH CHECK (owner_id = nullif(current_setting('app.current_user_id', true), '')::uuid);

CREATE POLICY evidence_owner_policy ON evidence_items
  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.id = profile_id))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles p WHERE p.id = profile_id));
CREATE POLICY charts_owner_policy ON chart_snapshots
  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.id = profile_id))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles p WHERE p.id = profile_id));
CREATE POLICY runs_owner_policy ON analysis_runs
  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.id = profile_id))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles p WHERE p.id = profile_id));
CREATE POLICY relation_owner_policy ON relationship_subjects
  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.id = profile_id))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles p WHERE p.id = profile_id));
CREATE POLICY journal_owner_policy ON journal_entries
  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.id = profile_id))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles p WHERE p.id = profile_id));
CREATE POLICY versions_owner_policy ON profile_versions
  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.id = profile_id))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles p WHERE p.id = profile_id));

COMMIT;
