-- V1 RC invitation issuance. Plain tokens are generated by the API and never
-- persisted; this function receives only a SHA-256 token hash.
CREATE OR REPLACE FUNCTION create_invitation(
  p_id uuid,
  p_token_hash text,
  p_role text,
  p_expires_hours integer
) RETURNS timestamptz
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_expires_at timestamptz;
BEGIN
  IF app_current_user_role() <> 'owner' THEN
    RAISE EXCEPTION 'owner_only_invitation_creation';
  END IF;
  IF p_role NOT IN ('member', 'viewer') THEN
    RAISE EXCEPTION 'invalid_invitation_role';
  END IF;
  IF p_expires_hours < 1 OR p_expires_hours > 168 THEN
    RAISE EXCEPTION 'invalid_invitation_expiry';
  END IF;
  v_expires_at := now() + make_interval(hours => p_expires_hours);
  INSERT INTO invitations(id,token_hash,role,issued_by,expires_at)
    VALUES(p_id,p_token_hash,p_role,app_current_user_id(),v_expires_at);
  RETURN v_expires_at;
END
$$;

REVOKE ALL ON FUNCTION create_invitation(uuid,text,text,integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION create_invitation(uuid,text,text,integer) TO app_runtime;
